### ISSUE TITLE
Redox build fails (osx)

### ISSUE THREAD

**Issue by dwhit** [redox-os/redox#560] opened 2016-03-19 16:03 UTC
hey, 

``make -j 4 build`` returns ``make: Nothing to be done for `build'.``

``make qemu`` returns ``error: could not exec the linker `i386-elf-gcc`: No such file or directory (os error 2)``

all the different make commands (all, qemu, qemu kvm=no) give that same linker error

**Comment by Ticki** [comment] 2016-03-19 16:04
Try to compile x86_64 version instead.

**Comment by jackpot51** [comment] 2016-03-19 16:05
You need to install i386-elf-gcc with either homebrew or macports

**Comment by slayerjain** [comment] 2016-03-19 16:20
I faced a similar issue but, there's no i386-elf-gcc package in homebrew.

**Comment by djmadeira** [comment] 2016-03-19 16:31
You can `brew tap jinmel/homebrew-gcc_cross_compilers` to get a bunch of homebrew scripts for this, but `brew install i386-elf-gcc` fails for me with: 

```
couldn't understand kern.osversion `15.3.0'
config.status: executing default commands
make: *** [all] Error 2
```

**Comment by djmadeira** [comment] 2016-03-19 16:49
I also tried [this script](https://gist.github.com/jtauber/8b2fa862d43ecedf7536), but that failed for me as well.

**Comment by djmadeira** [comment] 2016-03-19 17:08
Seems like this issue is a dupe of #40. One of them should stay open though, since I'm not able to make the instructions on #40 work either.

**Comment by lmb** [comment] 2016-03-20 21:54
These instructions are from @esell in #165 

```bash
brew tap sevki/homebrew-gcc_cross_compilers
brew install sevki/gcc_cross_compilers/x86_64-elf-binutils
brew install sevki/gcc_cross_compilers/x86_64-elf-gcc
export ARCH=x86_64
make -j4 all
make qemu kvm=no
```

That gets you a Redox that boots into a shell. Orbital doesn't want to launch it seems like, however.

**Comment by simon-whitehead** [comment] 2016-03-24 06:07
I had this same problem but, after finally getting it building and running I too can't seem to launch Orbital. It tries.. dumps a heap of information to the Terminal... then finally crashes. I'll monitor this for a few more days before opening my own issue.

**Comment by jackpot51** [comment] 2016-04-29 22:55
The build works fine for me now, the issues are fixed

**Closed by jackpot51** 2016-04-29 22:55 UTC
