### ISSUE TITLE
Mouse slowdown and phantom clicks

### ISSUE THREAD

**Issue by xTibor** [redox-os/redox#771] opened 2016-12-02 00:26 UTC
The biggest issue I found while tinkering with the live ISO. When I open `file:/bin/` in the File Manager, the mouse slows down over the window. After moving it up and down there for a while the mouse jumps to the bottom left corner of the screen and the system registers random phantom clicks.

I may be wrong, but according to the `ps2d: overflow` and `MOUSE MISALIGN` messages on the kernel log this might be a ps2d issue.

**Reproduction**:
* https://youtu.be/89YOnv11rtE
* VirtualBox settings are default except:
  * 2048 MiB RAM
  * SATA HDD controller
  * A bridged network adapter

**Build information**:
* VirtualBox 5.0.24 (on Kubuntu 16.04)
* Latest Redox ISO

**Comment by jackpot51** [comment] 2016-12-02 00:29
You are right. Probably the disk driver is thrashing with the ps2 driver, causing this problem.

**Comment by jackpot51** [comment] 2017-02-08 05:56
Please try the latest release: https://github.com/redox-os/redox/releases/tag/0.0.8

**Comment by xTibor** [comment] 2017-02-08 15:13
Unfortunately, it's still reproducible the same way as before: http://i.imgur.com/u0gg3Ga.png

**Comment by Csega** [comment] 2017-03-03 11:18
Hi all!

I have the same problem still with the latest release. I use "make qemu kvm=no" command to run Redox, everything goes with the default settings.

**Comment by polymetric1** [comment] 2017-03-05 00:40
Csega, you're building from the Git repository, which is newer than the latest release, but technically not the latest "release" (unless you're using tags). I just want to clarify that.

**Comment by Csega** [comment] 2017-03-05 07:50
Sorry, my bad, you're right. I'm building from the Git repo using the HEAD revision.

**Comment by jackpot51** [comment] 2017-03-17 05:14
Does this still happen?

**Comment by Csega** [comment] 2017-03-19 21:45
It is better now, but the problem still persists. Better in the sense, that it is more robust. In the earlier versions the cursor went out of the screen very easily. Now I could open the image viewer app, resize the window and close it, and the cursor disappeared just after these operations. So it is definitely better, but still not perfect.

**Comment by xTibor** [comment] 2017-04-10 19:46
I cannot reproduce it anymore with 0.1.5.

**Comment by jackpot51** [comment] 2017-04-13 12:54
There is a similar issue here: https://github.com/redox-os/redox/issues/886

@Csega Running without KVM acceleration will have slower performance, that could be your issue.

**Comment by Csega** [comment] 2017-04-17 10:54
I tried the latest commit and the mouse does not disappear. However, when there is a heavy load on the system, it can jump, but that's probably caused by the lack of KVM.

**Comment by jackpot51** [comment] 2017-04-17 12:34
Ok, cool

**Closed by jackpot51** 2017-04-17 12:34 UTC
