### ISSUE TITLE
When I execute `sudo make virtualbox`, just show a Redox image background.

### ISSUE THREAD

**Issue by origel** [redox-os/redox#776] opened 2016-12-05 05:58 UTC
start up log seems OK.

$ sudo make virtualbox
[sudo] password for work: 
#filesystem/bin/shutdown filesystem/bin/test
fusermount -u build/filesystem/
fusermount: failed to unmount /home/work/linux/redox/build/filesystem: No such file or directory
make: [build/filesystem.bin] Error 1 (Ignore)
rm -rf build/filesystem.bin build/filesystem/
echo exit | cargo run --manifest-path schemes/redoxfs/Cargo.toml --bin redoxfs-utility build/filesystem.bin 128
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `schemes/redoxfs/target/debug/redoxfs-utility build/filesystem.bin 128`
redoxfs: created filesystem build/filesystem.bin
redoxfs# mkdir -p build/filesystem/
cargo build --manifest-path schemes/redoxfs/Cargo.toml --bin redoxfs-fuse --release
    Finished release [optimized] target(s) in 0.0 secs
schemes/redoxfs/target/release/redoxfs-fuse build/filesystem.bin build/filesystem/ &
sleep 2
redoxfs: opened filesystem build/filesystem.bin
pgrep redoxfs-fuse
30748
cp -RL filesystem/* build/filesystem/
chown -R 0:0 build/filesystem
chown -R 1000:1000 build/filesystem/home/user
chmod -R uog+rX build/filesystem
chmod -R u+w build/filesystem
chmod -R og-w build/filesystem
chmod -R 755 build/filesystem/bin
chmod -R u+rwX build/filesystem/root
chmod -R og-rwx build/filesystem/root
chmod -R u+rwX build/filesystem/home/user
chmod -R og-rwx build/filesystem/home/user
chmod +s build/filesystem/bin/passwd
chmod +s build/filesystem/bin/su
chmod +s build/filesystem/bin/sudo
mkdir build/filesystem/tmp
chmod 1777 build/filesystem/tmp
sync
fusermount -u build/filesystem/
rm -rf build/filesystem/
nasm -f bin -o build/harddrive.bin -D ARCH_x86_64 -ibootloader/x86_64/ bootloader/x86_64/harddrive.asm
echo "Delete VM"
Delete VM
VBoxManage unregistervm Redox --delete; \
	if [ $? -ne 0 ]; \
	then \
		if [ -d "$HOME/VirtualBox VMs/Redox" ]; \
		then \
			echo "Redox directory exists, deleting..."; \
			rm -f -rf "$HOME/VirtualBox VMs/Redox"; \
		fi \
	fi
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
echo "Delete Disk"
Delete Disk
rm -f harddrive.vdi
echo "Create VM"
Create VM
VBoxManage createvm --name Redox --register
Virtual machine 'Redox' is created and registered.
UUID: 02682db8-97c3-49a6-a5e0-7d4a68b50943
Settings file: '/root/VirtualBox VMs/Redox/Redox.vbox'
echo "Set Configuration"
Set Configuration
VBoxManage modifyvm Redox --memory 1024
VBoxManage modifyvm Redox --vram 16
VBoxManage modifyvm Redox --nic1 nat
VBoxManage modifyvm Redox --nictype1 82540EM
VBoxManage modifyvm Redox --cableconnected1 on
VBoxManage modifyvm Redox --nictrace1 on
VBoxManage modifyvm Redox --nictracefile1 build/network.pcap
VBoxManage modifyvm Redox --uart1 0x3F8 4
VBoxManage modifyvm Redox --uartmode1 file build/serial.log
VBoxManage modifyvm Redox --usb off # on
VBoxManage modifyvm Redox --keyboard ps2
VBoxManage modifyvm Redox --mouse ps2
VBoxManage modifyvm Redox --audio "pulse"
VBoxManage modifyvm Redox --audiocontroller ac97
echo "Create Disk"
Create Disk
VBoxManage convertfromraw build/harddrive.bin build/harddrive.vdi
Converting from raw image file="build/harddrive.bin" to file="build/harddrive.vdi"...
Creating dynamic image with size 135755776 bytes (130MB)...
echo "Attach Disk"
Attach Disk
VBoxManage storagectl Redox --name ATA --add sata --controller IntelAHCI --bootable on --portcount 1
VBoxManage storageattach Redox --storagectl ATA --port 0 --device 0 --type hdd --medium build/harddrive.vdi
echo "Run VM"
Run VM
VBoxManage startvm Redox
Waiting for VM "Redox" to power on...
VM "Redox" has been successfully started.

**Comment by origel** [comment] 2016-12-05 06:06
70% will stay in a Redox Background.  and sometimes work normal.

**Comment by jackpot51** [comment] 2016-12-12 20:47
Could everyone still running into problems try the newest release? https://github.com/redox-os/redox/releases/tag/0.0.4

**Comment by jackpot51** [comment] 2017-03-17 05:10
Duplicate of https://github.com/redox-os/redox/issues/868

**Closed by jackpot51** 2017-03-17 05:10 UTC
