### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by glowing-chemist** [redox-os/redox#637] opened 2016-05-12 21:46 UTC
**Reproduction**: 
running comand "make all" fails after three errors. on amd64 arch linux.
make clean and git clean don't help either.

terminal prints:

mkdir -p build/i386-unknown-redox/debug
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -o build/i386-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs
rust/src/libcore/num/bignum.rs:43:5: 43:75 error: the trait bound `Self: marker::Sized` is not satisfied
rust/src/libcore/num/bignum.rs:43     fn full_mul(self, other: Self, carry: Self) -> (Self /*carry*/, Self);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/num/bignum.rs:43:5: 43:75 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
rust/src/libcore/num/bignum.rs:43:5: 43:75 note: for more information, see issue #33242 <https://github.com/rust-lang/rust/issues/33242>
rust/src/libcore/lib.rs:60:31: 60:39 note: lint level defined here
rust/src/libcore/lib.rs:60 #![cfg_attr(not(stage0), deny(warnings))]
                                                         ^~~~~~~~
rust/src/libcore/num/bignum.rs:47:5: 47:93 error: the trait bound `Self: marker::Sized` is not satisfied
rust/src/libcore/num/bignum.rs:47     fn full_mul_add(self, other: Self, other2: Self, carry: Self) -> (Self /*carry*/, Self);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/num/bignum.rs:47:5: 47:93 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
rust/src/libcore/num/bignum.rs:47:5: 47:93 note: for more information, see issue #33242 <https://github.com/rust-lang/rust/issues/33242>
rust/src/libcore/lib.rs:60:31: 60:39 note: lint level defined here
rust/src/libcore/lib.rs:60 #![cfg_attr(not(stage0), deny(warnings))]
                                                         ^~~~~~~~
rust/src/libcore/num/bignum.rs:51:5: 51:97 error: the trait bound `Self: marker::Sized` is not satisfied
rust/src/libcore/num/bignum.rs:51     fn full_div_rem(self, other: Self, borrow: Self) -> (Self /*quotient*/, Self /*remainder*/);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/num/bignum.rs:51:5: 51:97 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
rust/src/libcore/num/bignum.rs:51:5: 51:97 note: for more information, see issue #33242 <https://github.com/rust-lang/rust/issues/33242>
rust/src/libcore/lib.rs:60:31: 60:39 note: lint level defined here
rust/src/libcore/lib.rs:60 #![cfg_attr(not(stage0), deny(warnings))]
                                                         ^~~~~~~~
error: aborting due to 3 previous errors
Makefile:422: recipe for target 'build/i386-unknown-redox/debug/libcore.rlib' failed
make: *** [build/i386-unknown-redox/debug/libcore.rlib] Error 101

uname = Linux "name" 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux
rustc -V = rustc 1.10.0-nightly (e0fd34bba 2016-05-09)

thanks.

**Comment by ca1ek** [comment] 2016-05-13 05:56
Same error on 64-bit Linux Mint on latest nightly.

-----Wiadomość oryginalna-----
Od: "Oliver Smith" <notifications@github.com>
Wysłano: ‎2016-‎05-‎12 23:46
Do: "redox-os/redox" <redox@noreply.github.com>
Temat: [redox-os/redox] Failed to build (#637)

Reproduction: 
running comand "make all" fails after three errors. on amd64 arch linux.
make clean and git clean don't help either.
terminal prints:
mkdir -p build/i386-unknown-redox/debug
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -o build/i386-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs
rust/src/libcore/num/bignum.rs:43:5: 43:75 error: the trait bound Self: marker::Sized is not satisfied
rust/src/libcore/num/bignum.rs:43 fn full_mul(self, other: Self, carry: Self) -> (Self /carry/, Self);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/num/bignum.rs:43:5: 43:75 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
rust/src/libcore/num/bignum.rs:43:5: 43:75 note: for more information, see issue #33242 rust-lang/rust#33242
rust/src/libcore/lib.rs:60:31: 60:39 note: lint level defined here
rust/src/libcore/lib.rs:60 #![cfg_attr(not(stage0), deny(warnings))]
^~~~~~~~
rust/src/libcore/num/bignum.rs:47:5: 47:93 error: the trait bound Self: marker::Sized is not satisfied
rust/src/libcore/num/bignum.rs:47 fn full_mul_add(self, other: Self, other2: Self, carry: Self) -> (Self /carry/, Self);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/num/bignum.rs:47:5: 47:93 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
rust/src/libcore/num/bignum.rs:47:5: 47:93 note: for more information, see issue #33242 rust-lang/rust#33242
rust/src/libcore/lib.rs:60:31: 60:39 note: lint level defined here
rust/src/libcore/lib.rs:60 #![cfg_attr(not(stage0), deny(warnings))]
^~~~~~~~
rust/src/libcore/num/bignum.rs:51:5: 51:97 error: the trait bound Self: marker::Sized is not satisfied
rust/src/libcore/num/bignum.rs:51 fn full_div_rem(self, other: Self, borrow: Self) -> (Self /quotient/, Self /remainder/);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/num/bignum.rs:51:5: 51:97 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
rust/src/libcore/num/bignum.rs:51:5: 51:97 note: for more information, see issue #33242 rust-lang/rust#33242
rust/src/libcore/lib.rs:60:31: 60:39 note: lint level defined here
rust/src/libcore/lib.rs:60 #![cfg_attr(not(stage0), deny(warnings))]
^~~~~~~~
error: aborting due to 3 previous errors
Makefile:422: recipe for target 'build/i386-unknown-redox/debug/libcore.rlib' failed
make: *** [build/i386-unknown-redox/debug/libcore.rlib] Error 101
uname = Linux "name" 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux
rustc -V = rustc 1.10.0-nightly (e0fd34bba 2016-05-09)
thanks.

**Comment by bjorn3** [comment] 2016-05-13 18:02
I think the libcore fork should be updated.

**Comment by jackpot51** [comment] 2016-05-13 19:28
Rust has been updated and build issues are fixed with latest nightly

**Closed by jackpot51** 2016-05-13 19:28 UTC
