### ISSUE TITLE
Orbital page faults after exec fails in terminal

### ISSUE THREAD

**Issue by skylerberg** [redox-os/redox#345] opened 2015-12-05 19:36 UTC
Steps to reproduce:

* Switch to desktop
* Open terminal
* Run the command `exec foo`
* Wait 2-3 seconds

A couple seconds after exec foo fails orbital will page fault and stop working.

Here is the output when orbital fails:
```
file:/foo: Failed to open
PID 7: file:/schemes/orbital/main.bin
  INT E: Page fault
    CS:  00000008    IP:  C0004185    FLG: 00010046
    SS:  00000000    SP:  C0015000    BP:  0180FEBC
    AX:  C149A000    BX:  00000001    CX:  00000001    DX:  00000002
    DI:  00000000    SI:  00000000
    CR0: 80000013    CR2: 00000029    CR3: 00200000    CR4: 00000600
    ERR: 00000002
```

**Comment by polymetric1** [comment] 2015-12-05 20:18
Didn't happen for me. I repeated it the exact same way. Ran `exec foo` from orbital desktop. Can you maybe give a bit more info?
- What VM are you using? Try using the alternative, just to see if that works.
- Have you updated your VM lately?
- What is your host OS?
- Are you building the buddy branch or master? If you're using buddy, try master.
It's probably a problem with qemu/virtualbox.

**Comment by skylerberg** [comment] 2015-12-05 20:28
Yeah, I am running Ubuntu 14.04 using qemu. Virtualbox is not working on my host at the moment, so I cannot test it. I am running on master. qemu is up to date on the system.

**Comment by Ticki** [comment] 2015-12-05 20:29
I ran into page faults multiple times (when debugging Sodium) however I'm unable to reproduce.

**Comment by skylerberg** [comment] 2015-12-05 20:33
I just realized it doesn't just page fault after a bit. I have to do something on orbital. For example, move my cursor around for a bit or minimize and maximize the window a couple times.

**Comment by Ticki** [comment] 2015-12-05 20:34
Are you in sync with master?

**Comment by skylerberg** [comment] 2015-12-05 20:36
Yes, I am in sync with upstream master.

**Comment by Ticki** [comment] 2015-12-05 20:37
Orbital needed some heavy refactoring anyways.

**Comment by polymetric1** [comment] 2015-12-05 20:40
Virtualbox is not working for me, either. Same version of Ubuntu. However my setup is Redox(qemu) running on Ubuntu(virtualbox) running on Windows(host), which I feel like would cause more errors.
It's not a problem with qemu, then, anyway. Page faults seem to occur rather commonly, but are not easily reproducable and seem random. I just got one simply by opening the terminal in orbital.

**Comment by Ticki** [comment] 2015-12-05 20:44
It seems to be introduced lately (maybe with the merge of `real_hardware`?). I'm looking through liborbital with `git blame`.

**Comment by LazyOxen** [comment] 2015-12-05 23:14
If you do the same `exec foo` from the console, then you can no longer enter commands there; however, you can still switch to orbital.

There seem to be 2 things at play here:
1. File existence
2. Validity of file attempting to spawn. For example, if the file exists, it must be a valid executable as well (after submitting the PR I realized you would get similar behaviour when attempting to `exec` a folder).

What level should this be addressed at?
In my PR I put it in the code for Command::spawn, but it seems as though this validation should occur at the OS level rather than library level. Any thoughts?

**Comment by skylerberg** [comment] 2015-12-05 23:20
My concern is mostly at the orbital level. Something behaving poorly in it shouldn't cause it to crash and freeze up.

**Comment by polymetric1** [comment] 2015-12-05 23:41
Something made everything very unstable. As Ticki said, it might have been the real_hardware merge. I'd say just take a look at all the stuff that was changed in real_hardware, see if it's anything in there

**Comment by Ticki** [comment] 2015-12-06 12:25
Can somebody checkout before real_hardware and see if they get any problems? I don't seem too get any, can somebody confirm?

**Comment by jackpot51** [comment] 2015-12-16 21:11
This is fixed in the latest master

**Closed by jackpot51** 2015-12-16 21:11 UTC
