### ISSUE TITLE
It can't run in VMware Workstation 12 (Windows 10)

### ISSUE THREAD

**Issue by 3442853561** [redox-os/redox#821] opened 2017-01-08 05:43 UTC
It can't run in VMware Workstation 12 (Windows 10)
Nothing at all after I choose the interface size

**Comment by cxleb** [comment] 2017-01-17 23:09
same for VirtualBox

**Comment by electrodeyt** [comment] 2017-02-05 00:13
Same here.
It terminates saying that the CPU was halted.
Wonder why it executes a HLT.

**Comment by jackpot51** [comment] 2017-02-08 05:50
Please try again with release 0.0.8: https://github.com/redox-os/redox/releases/tag/0.0.8

**Comment by 3442853561** [comment] 2017-02-09 05:29
@jackpot51 It can't not run(0.0.8)

**Comment by Mm7** [comment] 2017-02-22 18:24
@jackpot51 On VirtualBox 5.1 (Debian linux) redox (HEAD, as of 22 February 2017) hangs due to dhpcd.
![screenshot from 2017-02-22 19-22-07](https://cloud.githubusercontent.com/assets/3750483/23225984/3fff9efc-f934-11e6-810d-0da89c2a78ae.png)

By disabling dhcpd from /etc/init.d/10_net I can reach orbit

**Comment by polymetric1** [comment] 2017-02-22 19:44
This is happening on most Redox builds ATM. It's something to do with the network drivers.

**Comment by jackpot51** [comment] 2017-03-17 05:09
Duplicate of https://github.com/redox-os/redox/issues/868

**Closed by jackpot51** 2017-03-17 05:09 UTC
