### ISSUE TITLE
There is no auto test, I am afraid of the stablitiy

### ISSUE THREAD

**Issue by lygstate** [redox-os/redox#454] opened 2016-01-13 15:44 UTC

**Comment by Ticki** [comment] 2016-01-13 16:43
I don't understand?

**Comment by lygstate** [comment] 2016-01-13 17:20
There is no CI test like servo did, there would be a auto-test for each merge-request.

**Comment by hauleth** [comment] 2016-01-13 17:26
@lygstate there are some things worth mentioning:

- Redox is much more complex than Servo so tests will be much more complex. For now we focus on functionality, not tests.
- Redox is on early stage of development, so we focus on functionality, not tests.
- Testing environment for Redox is much more complicated than Servo (Servo doesn't need to be run inside VM) so we focus on functionality, not tests.
- I believe there is no possibility to run Qemu or any other VM on any known publicly available CI, so until we get some serious funding (and be able to setup own CI server), we focus on functionality, not tests.

You see the pattern?

**Comment by jackpot51** [comment] 2016-01-13 17:32
The major issue is that testing an OS is not as simple as throwing in a #[test]. As we already have issues referencing testing, #396, and this issue uses a silly emotional appeal "I am afraid of the stability", I will close it.

Besides, Redox is very young, of course it is not stable yet. We will have to move much further before having any promise of stability

**Closed by jackpot51** 2016-01-13 17:32 UTC

**Comment by jcrben** [comment] 2016-09-11 04:55
You should consider automatically testing functionality. Otherwise you may find that when you take a step forward, you also take a step backward due to regressed functionality. Hope you're thinking about it. You could write scripts which boot up the system and try various functionality (end to end tests). Even if they are too slow to run on every pull request, it would be better than nothing. However, unit tests which simply test implementation details (mocks which ensure functions are called and so forth) are not as helpful at preventing regressions.

**Comment by Mouvedia** [comment] 2016-09-16 07:26
@jackpot51 [food for thought](https://reactos.org/testman/)

**Comment by ticki** [comment] 2016-09-16 10:40
@jcrben @Mouvedia Obviously, Redox is not going to be untested forever, and we're already looking into things like randomized testing, acid testing, and unit testing. Currently, we only have integration testing due to technical limitations (lack of libtest, as @jackpot51 pointed out). This is not as convinient due to being placedat one place instead next to the function itself.

**Comment by ticki** [comment] 2016-09-16 10:41
Many of the userspace libraries contains lots of test (look at ralloc, which has a 100% test coverage).

**Comment by jcrben** [comment] 2016-09-16 15:10
@ticki can you point to the integration tests?

**Comment by ticki** [comment] 2016-09-16 16:15
@jcrben https://github.com/redox-os/redox/tree/master/kernel/schemes/sys/test

It's an incredibly simple test system based on some macros I wrote, and honestly there are fewer tests than I recall...

**Comment by jcrben** [comment] 2016-09-16 16:17
Cool. In my opinion, number one priority would be to get some basic end-to-end "black box" smoke tests up to make sure that no critical functionality is ever broken for users.

**Comment by ticki** [comment] 2016-09-16 16:20
There's also [this](https://github.com/redox-os/acid) small collection of acid tests @jackpot51 wrote.

**Comment by ticki** [comment] 2016-09-16 16:21
@jcrben, but I agree; and it is a focus of ours to get some tests, hopefully an extensive set of tests to catch critical bugs.
