### ISSUE TITLE
Kernel panic with no ethernet

### ISSUE THREAD

**Issue by Lewiscowles1986** [redox-os/redox#773] opened 2016-12-02 02:26 UTC
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Remove all ethernet devices from VirtualBox, start live-cd

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
OS to boot and self-assign local loopback address only, ignoring lack of ethernet

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
Kernel panic
![image](https://cloud.githubusercontent.com/assets/2605791/20820892/94118ec2-b836-11e6-8a87-2d709368d088.png)

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
N/A (binary run using 0.3 pre-release iso)

**Blocking/related**: [issues or PRs blocking or being related to this issue.]
Unknown

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
N/A

**Comment by Lewiscowles1986** [comment] 2016-12-02 02:30
OS: Ubuntu Xenial all updates applied
CPU: Intel i7 4700MQ
RAM: 16GB (1024MB assigned VM)
Virtualbox version: 
![image](https://cloud.githubusercontent.com/assets/2605791/20820960/059d52ec-b837-11e6-90e3-64df4571ff7f.png)

![image](https://cloud.githubusercontent.com/assets/2605791/20821009/3bc647a2-b837-11e6-8232-ba84c5c7fc39.png)

**Comment by K-Finlay** [comment] 2016-12-02 03:32
I am having the exact same thing occur here in Gnome Boxes 3.20.2.

OS: Fedora 24
CPU: Intel i7-2700K

**Comment by teaearlgraycold** [comment] 2016-12-02 03:57
Same issue on Windows 10, i5-2500K. Tried setting the network adapter as spec'd in the release notes.

**Comment by mzji** [comment] 2016-12-02 08:13
For the currently working VirtualBox configuration, please check #766 for the details.

**Comment by Lewiscowles1986** [comment] 2016-12-02 10:19
I knew when I reported it that it works with the specified hardware, but a kernel panic with no hardware?

**Comment by mzji** [comment] 2016-12-02 10:32
@Lewiscowles1986 Ah, misinterpreted your issue, sorry.
Looks like a hard-coded case in the code to get a Ethernet adapter.

**Comment by Lewiscowles1986** [comment] 2016-12-02 12:24
np, it was exactly the hard-coded I was worried about if an issue was not raised at some point it could lead to tears, I don't think it's urgent at this point

**Comment by jackpot51** [comment] 2016-12-02 13:54
I believe this is a duplicate of#764

**Closed** 2016-12-02 13:55 UTC
