### ISSUE TITLE
Frozend, graphical UI

### ISSUE THREAD

**Issue by razorTwo** [redox-os/redox#834] opened 2017-01-31 14:55 UTC
I try version 006 in Hyper-V on Windows 10
Without Mouse in ui i can change to terminal an login, without problem
But with mouse, the orbital login, also the terminal are freezed

thx help

**Comment by jackpot51** [comment] 2017-02-08 05:56
Please try the latest release: https://github.com/redox-os/redox/releases/tag/0.0.8

**Comment by Thetoxicarcade** [comment] 2017-02-14 09:21
Latest commits (#52d640b for example) should work. :)

**Comment by jackpot51** [comment] 2017-03-17 05:10
Duplicate of https://github.com/redox-os/redox/issues/868

**Closed by jackpot51** 2017-03-17 05:10 UTC
