### ISSUE TITLE
It won't start in VirtualBox

### ISSUE THREAD

**Issue by mihail-mojsoski** [redox-os/redox#802] opened 2017-01-01 17:04 UTC
**Reproduction**: 
When i create a Virtual Machine in VM Virtualbox as Windows or Linux it doesn't work.

**Expected behavior**:
I expect it to boot correctly.

**Build information**:
I use the release 0.0.5 ISO on `VirtualBox VM 5.1.6_Ubuntu r110634 linux.amd64`

**Actual behavior**:
It fails with this error message:
```
A critical error has occurred while running the virtual machine and the machine execution has been stopped.
For help, please see the Community section on https://www.virtualbox.org or your support contract. Please provide the contents of the log file VBox.log and the image file VBox.png, which you can find in the /home/mihail/VirtualBox VMs/Redox/Logs directory, as well as a description of what you were doing when this error happened. Note that you can also access the above files by selecting Show Log from the Machine menu of the main VirtualBox window.
Press OK if you want to power off the machine or press Ignore if you want to leave it as is for debugging. Please note that debugging requires special knowledge and tools, so it is recommended to press OK now.
```

<details> 
  <summary>Log </summary>
<code><pre>
VirtualBox VM 5.1.6_Ubuntu r110634 linux.amd64 (Sep 14 2016 06:43:10) release log
00:00:00.502887 Log opened 2017-01-01T16:57:27.881712000Z
00:00:00.502889 Build Type: release
00:00:00.502893 OS Product: Linux
00:00:00.502894 OS Release: 4.8.0-32-generic
00:00:00.502895 OS Version: #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016
00:00:00.502923 DMI Product Name: G41MT-S2
00:00:00.502934 DMI Product Version:  
00:00:00.502991 Host RAM: 7982MB total, 6117MB available
00:00:00.502995 Executable: /usr/lib/virtualbox/VirtualBox
00:00:00.502996 Process ID: 8561
00:00:00.502997 Package type: LINUX_64BITS_GENERIC (OSE)
00:00:00.531803 Installed Extension Packs:
00:00:00.531831   VNC (Version: 5.1.6 r110634; VRDE Module: VBoxVNC)
00:00:00.532644 Console: Machine state changed to 'Starting'
00:00:00.532908 Qt version: 5.6.1
For the full log to to: http://pastebin.com/raw/gaf5s8Pm
</pre></code>
</details>

**Comment by FaraoneLele** [comment] 2017-01-01 17:38
same problem on windows

**Comment by bjorn3** [comment] 2017-01-01 17:54
All settings set according to the example config at https://github.com/redox-os/redox/releases/tag/0.0.3

**Comment by mihail-rotmg** [comment] 2017-01-01 19:19
I also tried downgrading to 0.0.3 and using the Example Configuration on both ISOs

**Comment by jackpot51** [comment] 2017-01-02 14:55
This appears to be related to paging - I have been able to reproduce this issue so I will be trying to fix it.

**Comment by jackpot51** [comment] 2017-01-02 16:37
@mihail-rotmg @FaraoneLele if you are able, please set serial port 1 to a file, then attempt to boot Redox once, then post that file here.

**Comment by FaraoneLele** [comment] 2017-01-02 17:00
I don't know how to do this

**Comment by PeterJCLaw** [comment] 2017-01-02 17:44
Assuming that you're using the VirtualBox GUI, the serial ports are controlled in the "Serial Ports" section of the "Settings" dialog for the VM you've created. You can choose to enable any of them (you probably want to choose the first).

I expect from what @jackpot51 has said you should choose the first, leave the "Port Number" setting as `COM1` but set the "Port Mode" to `Raw File`. In the "Path/Address" field you'll want to set a path on the host where VirtualBox can write out the data it receives.

Doing this for me (I'm also having issues with VirtualBox and am using the 0.0.5 ISO, though it doesn't crash in the manner you're describing) gives:
```
MemoryArea { base_addr: 0, length: 651264, _type: 1, acpi: 0 }
MemoryArea { base_addr: 651264, length: 4096, _type: 2, acpi: 0 }
MemoryArea { base_addr: 983040, length: 65536, _type: 2, acpi: 0 }
MemoryArea { base_addr: 1048576, length: 1473738752, _type: 1, acpi: 0 }
MemoryArea { base_addr: 1474787328, length: 135759872, _type: 2, acpi: 0 }
MemoryArea { base_addr: 1610547200, length: 65536, _type: 3, acpi: 0 }
MemoryArea { base_addr: 4273995776, length: 4096, _type: 2, acpi: 0 }
MemoryArea { base_addr: 4276092928, length: 4096, _type: 2, acpi: 0 }
MemoryArea { base_addr: 4294705152, length: 262144, _type: 2, acpi: 0 }
XSDT:
  FACP: Unknown
  APIC: FEE00000: 1
    XAPIC 0: FFFFFF00FEE00000
      IntSrcOverride(MadtIntSrcOverride { bus_source: 0, irq_source: 0, gsi_base: 2, flags: 0 })
      IntSrcOverride(MadtIntSrcOverride { bus_source: 0, irq_source: 9, gsi_base: 9, flags: 13 })
      LocalApic(MadtLocalApic { processor: 0, id: 0, flags: 1 })
        This is my local APIC
      IoApic(MadtIoApic { id: 1, reserved: 0, address: 4273995776, gsi_base: 0 })
  SSDT: Unknown
BSP: Ok(ContextId(1)) 1
```
For reference that's from a run with the OS Type set to `Other`, with Version `Other/Unknown (64-bit)`, but changed to use an Intel 82540EM network card and 1536MB of RAM. I'm using VirtualBox 5.1.12 on Ubuntu 16.04.

**Comment by PeterJCLaw** [comment] 2017-01-02 18:14
(my issue seems to be mostly fixed by changing my VirtualBox config to that noted in https://github.com/redox-os/redox/issues/766#issuecomment-264359360)

**Comment by mominul** [comment] 2017-02-06 10:07
Hi, I am also having issues when booting Redox(0.0.7). Redox stops in this stage in Virtual Box:
![virtualbox_redoxos_ _ _ _ _ _](https://cloud.githubusercontent.com/assets/9459891/22642516/39942328-ec85-11e6-9d16-6e7dc5f5e0bc.png)
I have followed those two references posted by @jackpot51 and @mzji in issue #766, but there is no change.
Heres the com output (thanks @PeterJCLaw ):

```
MemoryArea { base_addr: 0, length: 651264, _type: 1, acpi: 0 }
MemoryArea { base_addr: 651264, length: 4096, _type: 2, acpi: 0 }
MemoryArea { base_addr: 983040, length: 65536, _type: 2, acpi: 0 }
MemoryArea { base_addr: 1048576, length: 1002927104, _type: 1, acpi: 0 }
MemoryArea { base_addr: 1003975680, length: 69700608, _type: 2, acpi: 0 }
MemoryArea { base_addr: 1073676288, length: 65536, _type: 3, acpi: 0 }
MemoryArea { base_addr: 4273995776, length: 4096, _type: 2, acpi: 0 }
MemoryArea { base_addr: 4276092928, length: 4096, _type: 2, acpi: 0 }
MemoryArea { base_addr: 4294705152, length: 262144, _type: 2, acpi: 0 }
XSDT:
  FACP: Fadt {
    header: Sdt {
        signature: [
            70,
            65,
            67,
            80
        ],
        length: 244,
        revision: 4,
        checksum: 254,
        oem_id: [
            86,
            66,
            79,
            88,
            32,
            32
        ],
        oem_table_id: [
            86,
            66,
            79,
            88,
            70,
            65,
            67,
            80
        ],
        oem_revision: 1,
        creator_id: 541872961,
        creator_revision: 97
    },
    firmware_ctrl: 1073676864,
    dsdt: 1073677616,
    reserved: 0,
    preferred_power_managament: 0,
    sci_interrupt: 9,
    smi_command_port: 17454,
    acpi_enable: 161,
    acpi_disable: 160,
    s4_bios_req: 0,
    pstate_control: 0,
    pm1a_event_block: 16384,
    pm1b_event_block: 0,
    pm1a_control_block: 16388,
    pm1b_control_block: 0,
    pm2_control_block: 0,
    pm_timer_block: 16392,
    gpe0_block: 16416,
    gpe1_block: 0,
    pm1_event_length: 4,
    pm1_control_length: 2,
    pm2_control_length: 0,
    pm_timer_length: 4,
    gpe0_ength: 2,
    gpe1_length: 0,
    gpe1_base: 0,
    c_state_control: 0,
    worst_c2_latency: 101,
    worst_c3_latency: 1001,
    flush_size: 0,
    flush_stride: 0,
    duty_offset: 0,
    duty_width: 0,
    day_alarm: 0,
    month_alarm: 0,
    century: 0,
    boot_architecture_flags: 3,
    reserved2: 0,
    flags: 1345
}
  APIC: FEE00000: 1
    XAPIC 0: FFFFFF00FEE00000
      IntSrcOverride(MadtIntSrcOverride { bus_source: 0, irq_source: 0, gsi_base: 2, flags: 0 })
      IntSrcOverride(MadtIntSrcOverride { bus_source: 0, irq_source: 9, gsi_base: 9, flags: 13 })
      LocalApic(MadtLocalApic { processor: 0, id: 0, flags: 1 })
        This is my local APIC
      IoApic(MadtIoApic { id: 1, reserved: 0, address: 4273995776, gsi_base: 0 })
  HPET: Unknown
  MCFG: Unknown
  SSDT: Unknown
BSP: Ok(ContextId(1)) 1
```
I have tried pressing F1-F4 but no results.

Thanks

**Comment by jackpot51** [comment] 2017-02-08 05:53
Please try the latest release: https://github.com/redox-os/redox/releases/tag/0.0.8

**Comment by jackpot51** [comment] 2017-03-17 05:10
Duplicate of https://github.com/redox-os/redox/issues/868

**Closed by jackpot51** 2017-03-17 05:10 UTC
