### ISSUE TITLE
Entire System Freeze 0.1.1 LiveCD

### ISSUE THREAD

**Issue by komawoyo** [redox-os/redox#867] opened 2017-03-08 15:47 UTC
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Click continuously to open any of the apps on the taskbar

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
the system will freeze - you will no longer be able to move your mouse

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
Should work regardless of how many apps are open (memory management?)
**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
Release 0.1.1

**Blocking/related**: [issues or PRs blocking or being related to this issue.]
n/a

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

This is most likely memory related issue, the system hits a wall much faster if I set the memory to 512MB compared to 1024MB in VirtualBox

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by jackpot51** [comment] 2017-03-17 05:10
Duplicate of https://github.com/redox-os/redox/issues/868

**Closed by jackpot51** 2017-03-17 05:10 UTC
