### ISSUE TITLE
VirtualBox boots livedisk.iso but it not responsive

### ISSUE THREAD

**Issue by ged15** [redox-os/redox#767] opened 2016-12-01 11:31 UTC
**Reproduction**: booted a 64-bit machine, 2048MB RAM on VBox 5.0.30

**Expected behavior**: RedoxOS booted and usable.

**Actual behavior**: RedoxOS splash screen displayed but mouse cursor does not move:
![image](https://cloud.githubusercontent.com/assets/4046456/20792430/f4a7a64c-b7c1-11e6-8e03-32f80e66d56d.png)

**Build information**: livedisk.iso 0.0.3

**Blocking/related**:

**Misc**:

**Comment by jackpot51** [comment] 2016-12-01 13:56
Is the mouse device set to PS/2?

**Comment by ged15** [comment] 2016-12-01 14:09
Yes:
![image](https://cloud.githubusercontent.com/assets/4046456/20796799/2df0587a-b7d8-11e6-9a1d-a493ea8c1899.png)

**Comment by jackpot51** [comment] 2016-12-01 14:12
What CPU does your host computer have?

**Comment by ged15** [comment] 2016-12-01 14:14
![image](https://cloud.githubusercontent.com/assets/4046456/20796904/d5105114-b7d8-11e6-81fb-c39b56e3a79f.png)

**Comment by jackpot51** [comment] 2016-12-01 14:16
Please try `sysctl -n machdep.cpu.brand_string`

**Comment by ged15** [comment] 2016-12-01 14:17
> Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz

**Comment by jackpot51** [comment] 2016-12-01 14:18
Thanks, I will try to replicate behavior. If I find the cause and/or fix it, I will let you know

**Comment by ged15** [comment] 2016-12-01 14:25
Thanks! And thanks for Redox! Awesomely inspiring project :)

**Comment by jackpot51** [comment] 2016-12-01 14:28
Thanks! Also, does F2 take you to a text console?

**Comment by ged15** [comment] 2016-12-01 14:37
No.

**Comment by rushmorem** [comment] 2016-12-01 17:16
I'm running into this same issue. `F2` doesn't take me to a text console either:-

```
~> lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            22
Model:                 0
Model name:            AMD E1-2100 APU with Radeon(TM) HD Graphics
Stepping:              1
CPU MHz:               800.000
CPU max MHz:           1000.0000
CPU min MHz:           800.0000
BogoMIPS:              1996.26
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt topoext perfctr_nb bpext perfctr_l2 arat hw_pstate proc_feedback npt lbrv svm_lock nrip_save tsc_scale flushbyasid decodeassists pausefilter pfthreshold vmmcall bmi1 xsaveopt
```

**Comment by gregkatz** [comment] 2016-12-02 00:47
Hi all,

I had this problem but I was able to get around it by disabling nested paging under system->acceleration in virtualbox.

**Comment by jackpot51** [comment] 2016-12-02 01:28
@gregkatz Thanks for the tip - maybe I can find the problem now

**Comment by ged15** [comment] 2016-12-02 08:18
Can confirm it works when nested paging is disabled! Thanks @gregkatz!

**Comment by watafalk** [comment] 2016-12-02 08:47
VirtualBox 5.1.10, without nested paging it just shows a blackscreen.

**Comment by paskal** [comment] 2016-12-02 22:54
Confirmed, macOS 10.12.1, with nested paging enabled I can see screen with cursor but nothing else, with nested paging disabled I observe black screen, F[1-4] doesn't work.

```
➜  ~  sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
# virtualbox 5.1.6 r110634 (Qt5.5.1)
```

**Comment by monsieursquirrel** [comment] 2016-12-03 11:41
Hi all

Just adding another report to this case. Running under virtualbox on OSX El Capitan. CPU is 2.2 GHz Intel Core i7. RAM 4GB with 1GB assigned to the VM.

**Comment by remram44** [comment] 2016-12-07 21:35
Same report here, splash with cursor that won't move when nested paging is enabled. Disabling it makes it work fine.

macOS 10.12.1, `Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz`

**Comment by pkphilip** [comment] 2016-12-10 10:36
I had the same problem but on Linux Mint 18 using Virtualbox Version 5.0.24_Ubuntu r108355 . The splash screen was appearing but the mouse was unresponsive and the login dialog did not appear.

Fixed it by disabling NAT and choosing "Host Only Adapter".

![screenshot from 2016-12-10 16-04-46](https://cloud.githubusercontent.com/assets/2462031/21072734/74ee00ee-bef2-11e6-8136-bd80da716fbf.png)

**Comment by jackpot51** [comment] 2016-12-12 20:47
Could everyone still running into problems try the newest release? https://github.com/redox-os/redox/releases/tag/0.0.4

**Comment by watafalk** [comment] 2016-12-13 07:41
With v0.0.4 I can log in with the trick from [#764](https://github.com/redox-os/redox/issues/764#issuecomment-264398877). (VirtualBox 5.1.10, No Paravirtualization + Nested Paging).

**Comment by ged15** [comment] 2016-12-13 08:28
With 0.0.4 and nested paging enabled the OS still freezes, just at another screen:

![image](https://cloud.githubusercontent.com/assets/4046456/21132837/52d8381e-c116-11e6-8455-073a07eb1cc7.png)

**Comment by watafalk** [comment] 2016-12-13 08:55
@ged15 Ah, this happens very often [(with the trick)](https://github.com/redox-os/redox/issues/764#issuecomment-264398877) if I do not manually ESC the network boot.

![ESC](https://cloud.githubusercontent.com/assets/14152973/21133618/ad4e4552-c154-11e6-88ca-17ee41650dd8.png)

otherwise it stucks in the login screen.

**Comment by jackpot51** [comment] 2016-12-14 04:12
I fixed another potential issue in VirtualBox here: https://github.com/redox-os/redox/releases/tag/0.0.5

Please see if this fixes your issues.

**Comment by watafalk** [comment] 2016-12-14 08:45
@jackpot51 still need the network boot and manual ESC.

**Comment by Thetoxicarcade** [comment] 2016-12-14 17:36
@jackpot51 0.0.5 gets to this next frozen screen for me as well <3

**Comment by ca1ek** [comment] 2016-12-14 23:20
0.0.5, nested paging disabled, `Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz`, Debian 8 Stable, got a black screen in VBox

**Comment by jackpot51** [comment] 2017-02-08 05:54
Please try the latest release: https://github.com/redox-os/redox/releases/tag/0.0.8

**Comment by pkphilip** [comment] 2017-02-08 16:15
This works. I am able to log into the system and it seems to work well. Thanks!

**Comment by jackpot51** [comment] 2017-02-08 20:42
Cool!

**Comment by rushmorem** [comment] 2017-02-08 23:09
Now I'm able to login as well.

**Closed** 2017-02-09 14:04 UTC
