### ISSUE TITLE
Some issues with using redox

### ISSUE THREAD

**Issue by mahkoh** [redox-os/redox#295] opened 2015-11-19 14:52 UTC
I tried to use redox a bit and encountered the following issues.

#### Variables are hard-coded in the Makefile

I cannot use my normal rustc to compile redox so I installed a new nightly into a custom prefix. The makefile can then be made use the new rustc by replacing

```
RUSTC=RUST_BACKTRACE=1 rustc
```

with

```
RUSTC=RUST_BACKTRACE=1 redox-rustc
```

But since the Makefile is tracked by git this is a bit problematic. Instead, all of those variables should be read from a `config.mk` which is not tracked by git.

#### Redox is quite sluggish and uses 100% cpu

I tried it in both virtualbox and qemu (without kvm, which my system does not support). In virtualbox it is completely unusable. qemu is better but still slow. Either way it uses 100% cpu constantly. This looks like a bug.

#### Redox cannot be used without graphical output

I don't want to use the graphical output for various reasons:

* It's slow
* It doesn't understand my keyboard layout
* Fixed size windows don't work in my twm

It's almost possible to use redox without graphics but not quite. At the start it asks you to select an output size and waits for an answer. If you start it without graphics output, you cannot answer (maybe you can but I don't know qemu enough to do it). I fixed this with the following hack in vesa.asm:

```asm
	; int 0x16
	mov ax, 'y'
	pop esi
	cmp al, 'y'
	jne .searchmodes
```

With this I can use redox in qemu with the `-nographic` option. This makes redox much faster (but doesn't fix the 100% cpu issue.) Maybe an option could be added that completely disables the graphics part of the kernel?

**Comment by Ticki** [comment] 2015-11-19 14:55
All these are valid points, and performance definitely needs to be improved. Currently, I'm writing a new memory manager, because many of the performance issues are a result of inefficient memory management.

Orbital is no longer a part of the kernel. As such, the kernel is relatively small now.

Also, note that Redox is in its early state, and will improve over time.

**Comment by Ticki** [comment] 2015-11-19 14:56
Also, Redox runs better on real hardware.

**Comment by jackpot51** [comment] 2015-11-19 14:58
Sounds like you have a lot of problems with your current setup, rather than with Redox...

**Comment by Ticki** [comment] 2015-11-19 14:58
Redox *is* quite slow in VMs, though.

**Comment by jackpot51** [comment] 2015-11-19 14:59
This is not due to "inefficient memory management," rather, it is due to poor optimization of the graphics functions and interrupt handling that is not preemptible

**Comment by Ticki** [comment] 2015-11-19 15:00
My benchmarks of the allocations seems quite inefficient, but it might not be the cause of the slowness.

**Comment by jackpot51** [comment] 2015-11-19 15:01
Do a benchmark of Display::flip()

What was your allocation benchmark?

**Comment by Ticki** [comment] 2015-11-19 15:01
I don't have it anymore, since I'm an idiot and working on the master branch.

**Comment by jackpot51** [comment] 2015-11-19 15:06
Well, I will work on the 100% bug, I cannot do much about the -nographics because it is a critical part of the system for most users. The Makefile stuff can be worked around by submitting a PR with RUSTC?= instead of RUSTC= and then `source`ing your own variables

**Comment by jackpot51** [comment] 2015-11-19 15:12
There is a starvation bug in the UHCI touchscreen driver, it will be fixed and may improve performance.

**Comment by Ticki** [comment] 2015-11-19 15:55
@jackpot51: Here you got the benchmarks for flip() (in nanoseconds):

- min. 1379134 ns.
- max. 1385144 ns.
- avg. about 1370000 ns.

**Comment by mahkoh** [comment] 2015-11-19 16:12
>Sounds like you have a lot of problems with your current setup, rather than with Redox...

Possibly, but I've no problems when I try to run linux images. I'm very surprised that redox runs slower in virtualbox than in qemu. When I use them with linux, virtualbox is much, much faster.

>I cannot do much about the -nographics because it is a critical part of the system for most users.

I don't think those are mutually exclusive. Linux can be used in qemu with -nographic and without. The only issue here seems to be the required user-input at startup. When I disable it, redox becomes quite usable and fast, even on my system.

**Comment by jackpot51** [comment] 2015-11-19 16:39
The thing is, with that change, the display still gets setup and the display manager still runs, with whatever the first mode is, but Qemu does not create a window. So, it isn't as efficient as preventing the display manager from starting

**Comment by jackpot51** [comment] 2015-11-19 16:40
I am looking into speed issues, Virtualbox should be faster

**Comment by mahkoh** [comment] 2015-11-19 16:53
>So, it isn't as efficient as preventing the display manager from starting

I tested this and noticed that `-nographic` really doesn't improve the performance. What does improve the performance is to pass `-vga none` instead of `-vga std`. With `none`, `cat main.rs` works almost instantaneously. With `-vga std`, it takes more than 3 seconds.

**Comment by mahkoh** [comment] 2015-11-19 16:56
Oh, and with `-vga none` the kernel already skips the vesa code I had to edit. So you can actually already use the kernel with `-nographic` without having to edit anything.

**Comment by jackpot51** [comment] 2015-11-19 18:00
Following your advice, I have added a qemu_nographic Makefile target (in real_hardware branch where I am working on bug fixes)

**Comment by jackpot51** [comment] 2015-11-19 18:03
I also added a qemu_bare_no_vga for the absolute minimal. I realize that the number of Makefile targets are messy for qemu, oh well

**Comment by mahkoh** [comment] 2015-11-19 18:14
Instead of creating so many targets, one could have one qemu target which is then constructed by the makefile like this:

```
make qemu kvm=no vga=no display=no
```

**Comment by jackpot51** [comment] 2015-11-19 18:19
Yeah, that would be cool

**Closed** 2015-11-21 16:59 UTC
