### ISSUE TITLE
VirtualBox can not boot, panicked at failed to open network

### ISSUE THREAD

**Issue by frostRed** [redox-os/redox#764] opened 2016-11-28 04:52 UTC
VirtualBox have use Other/Unknown (64-bit) and SATA/AHCI.

![_2016-11-28_12-44-53](https://cloud.githubusercontent.com/assets/2486301/20656579/68ef2bd4-b569-11e6-8ffe-ea04883fb95c.png)

**Comment by jackpot51** [comment] 2016-11-28 13:35
Network card must be set to Intel 8254x

**Comment by Thetoxicarcade** [comment] 2016-11-29 03:36
I had a similar freeze on the DHCP for that last build that succeeded

**Comment by frostRed** [comment] 2016-11-30 04:08
selected Intel PRO/1000 MT Desktop (82540EM), but now a new problem arises like @Thetoxicarcade . DHCP not work well.

![_2016-11-30_11-57-58](https://cloud.githubusercontent.com/assets/2486301/20739305/5d27be7e-b6f4-11e6-8044-4d1c7e2f81d4.png)

**Comment by jackpot51** [comment] 2016-11-30 04:08
Press F2

**Comment by jackpot51** [comment] 2016-11-30 04:18
(Working on making orbital switch automatically)

**Comment by frostRed** [comment] 2016-11-30 04:26
Awesome OS, thank you all you guys.

**Comment by jackpot51** [comment] 2016-11-30 04:28
Thanks - feel free to create more issues when you find stuff!

**Comment by Thetoxicarcade** [comment] 2016-12-01 09:53
Whoops. @jackpot51 Sorry for being so much of a noob 💯

**Comment by Thetoxicarcade** [comment] 2016-12-01 10:23
Will virtual keys work for it? I have to hit [fn] & the f1 key on my device. Can I simply change the binding for that in my builds of it?

**Comment by jackpot51** [comment] 2016-12-01 14:29
If you are building from source, drivers/vesad is what has the binding and it can be changed

**Comment by fizyk20** [comment] 2016-12-01 21:06
As I've written on Reddit as `ebvalaim`, Redox gets stuck for me on `DHCP MAC ... Current IP ...`.

Host OS: Arch Linux
VirtualBox 5.1.10
CPU: Intel i7-4710HQ
VM type: Other/Unknown 64-bit
VM CPUs: 2
VM RAM: 1024 MB
VM Video RAM: 128 MB
Network card: Intel PRO 1000/MT Desktop (panics with other cards)

Not sure what else can be relevant - let me know if you need any other info.

**Comment by jackpot51** [comment] 2016-12-01 21:16
Thanks, that is good information.

**Comment by zekesonxx** [comment] 2016-12-01 23:15
I'm experiencing the same issue as @fizyk20. If I disable the ethernet adapter altogether, ethernetd panics

Same setup as fizyk, except i5-2320, and 1 VM CPU.

**Comment by beholdnec** [comment] 2016-12-01 23:19
I ran into frostRed's issue: Stuck at DHCP message, F-keys don't work. The problem disappeared when I changed RAM from 1024 MB to 2048 MB.

**Comment by beholdnec** [comment] 2016-12-01 23:57
So, before Redox can boot up in VirtualBox, some settings need to be changed. Here is a checklist:

In System:
- Set Base Memory to at least 1024 MB
- Set Chipset to ICH9 (This might be unnecessary...)

In Storage:
- Delete the IDE Controller. Add a SATA Controller. Attach an optical drive and load it with livedisk.iso.

In Network:
- Open the Advanced menu. Change Adapter Type to Intel PRO/1000 MT Desktop (82540EM).

At this point, Redox _might_ boot into a graphical UI, or it _might_ get stuck in DHCP. If it gets stuck, closing the VM and running it again might make it work eventually. I haven't found any pattern to when it gets stuck, but it seems to happen 90% of the time.

**Comment by butbutbut** [comment] 2016-12-02 05:08
Same as @fizyk20 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz

**Comment by vocivvy** [comment] 2016-12-02 08:20
I've been able to get passed the DHCP freeze by setting the boot order so that the Network goes before the Optical (Virtual Box). If I set the optical first, it gets stuck. Would this mean anything?

**Comment by watafalk** [comment] 2016-12-02 08:38
@vocivvy It does help to display the desktop with background and mouse, but then it just hangs like in #767 .

**Comment by githtz** [comment] 2016-12-09 12:41
@vocivvy Worked for me and did not hang afterwards!

**Comment by jackpot51** [comment] 2016-12-12 20:47
Could everyone still running into problems try the newest release? https://github.com/redox-os/redox/releases/tag/0.0.4

**Comment by fizyk20** [comment] 2016-12-12 21:48
Unfortunately, I get exactly the same symptoms (hangs on DHCP, panics without a card). @vocivvy's fix works, though (although I haven't tried it with the previous release).

**Comment by jackpot51** [comment] 2016-12-12 21:52
Interesting. Can you enable COM1, have it output to a file, and upload that file? More information about kernel faults is written to the serial console.

**Comment by githtz** [comment] 2016-12-13 12:04
[com.txt](https://github.com/redox-os/redox/files/648871/com.txt)
@jackpot51 Here you are (hope it helps!)

**Comment by githtz** [comment] 2016-12-13 12:10
@jackpot51 Here you are. 
[comcom.txt](https://github.com/redox-os/redox/files/648888/comcom.txt)

**Comment by bjorn3** [comment] 2016-12-13 12:40
```
Invalid opcode fault at 23:00000000004108D4
```

**Comment by githtz** [comment] 2016-12-13 12:44
I've just been playing around, changed some settings. Here are two log files, one with Network attached to NAT, one with Network set to not attached.
[boottodesk.txt](https://github.com/redox-os/redox/files/648961/boottodesk.txt)
[failed.txt](https://github.com/redox-os/redox/files/648962/failed.txt)

**Comment by bjorn3** [comment] 2016-12-13 13:03
@githtz you could try to debug it with http://www.virtualbox.org/manual/ch12.html#ts_debugger

**Comment by githtz** [comment] 2016-12-13 16:26
@bjorn3 Sorry, I lack the knowledge to use the debugger in any useful way. The logs provided by the debugger didn't provice any useful information to me either.

I've had a look at the source code and the debug output on the VM that has booted to desktop and the one that does not. The last debug message of the VM that booted to desktop is 

> DHCP: Sent Discover

while the last message of the other one is 

> DHCP: MAC: .... Current IP: ....

I guess the bug or at least a part of it is somewhere between [line 46](https://github.com/redox-os/netutils/blob/master/src/dhcpd/main.rs#L46) and [line 52](https://github.com/redox-os/netutils/blob/master/src/dhcpd/main.rs#L52) of the dhcpd-repository.
I also suspect there is some kind of loop running, since the CPU-usage of the VM that 'hangs' is on 100% for the assigned core.

**Comment by fizyk20** [comment] 2016-12-13 20:27
@jackpot51 I created 3 files:
* Output with the "hack" (network boot before optical): [redox_com1_hack.txt](https://github.com/redox-os/redox/files/650052/redox_com1_hack.txt)
* Output with a network card (hanging on DHCP): [redox_com1_card.txt](https://github.com/redox-os/redox/files/650053/redox_com1_card.txt)
* Output without a card (panic): [redox_com1_nocard.txt](https://github.com/redox-os/redox/files/650054/redox_com1_nocard.txt)

**Comment by jackpot51** [comment] 2016-12-14 04:12
I fixed another potential issue in VirtualBox here: https://github.com/redox-os/redox/releases/tag/0.0.5

Please see if this fixes your issues.

**Comment by zekesonxx** [comment] 2016-12-14 20:25
Been a while since I contributed to this, may as well.

Running 0.0.5 causes it to hang at DHCP again. Running 0.0.5 with Network above Optical in VirtualBox's boot order makes it work, and it doesn't eventually hang. Somehow.

**Comment by fizyk20** [comment] 2016-12-14 22:37
I got the same results as @zekesonxx.

**Comment by Coder206** [comment] 2017-01-08 02:06
@jackpot51 After playing around with no success running `0.0.6` release with the DHCP error as described above, I decided to start over to make sure I did everything correctly from the most current recommended for running in Virtual Box (I am on `v5.1.12`). However, I mistakenly left it to `PCnet-FAST III (NAT)` and ran the machine. Within moments Orbital showed up with a login screen and I was able to interact with Redox `0.0.6`.

**Comment by lehitoskin** [comment] 2017-02-03 01:29
I'm getting this error on release 0.0.7

**Comment by mominul** [comment] 2017-02-06 10:30
Hi, I am also having issues like others are when booting Redox(0.0.7). Redox stops in this stage in Virtual Box:
![virtualbox_redoxos_ _ _ _ _ _](https://cloud.githubusercontent.com/assets/9459891/22642516/39942328-ec85-11e6-9d16-6e7dc5f5e0bc.png)
Heres the com output:
[com-output.txt](https://github.com/redox-os/redox/files/754232/com-output.txt)

After trying @vocivvy hack, it goes this far:
![virtualbox_redoxos_ _ _ _ _ _](https://cloud.githubusercontent.com/assets/9459891/22643501/06d628ec-ec89-11e6-87ea-a70fb588511e.png)
[com-output.txt](https://github.com/redox-os/redox/files/754297/com-output.txt)

Heres VM Configuration:
![screenshot from 2017-02-06 16-29-49](https://cloud.githubusercontent.com/assets/9459891/22643659/98cdbc1a-ec89-11e6-8593-68b1f33f985b.png)

**Comment by paiv** [comment] 2017-02-07 00:01
Same here on 0.0.7 liveiso. macOS VirtualBox, stops on "DHCP: Sent Discover"

0.0.6 runs smoothly.

**Comment by polymetric1** [comment] 2017-02-07 05:27
Can confirm, getting the same DHCP error on 0.0.7.

**Comment by mominul** [comment] 2017-02-07 09:42
Can confirm that without @vocivvy 's hack 0.0.6 version also stop booting like version 0.0.7 is doing(`DHCP MAC ... Current IP ...`).

**Comment by jackpot51** [comment] 2017-02-08 05:54
Please try the latest release: https://github.com/redox-os/redox/releases/tag/0.0.8

**Comment by mominul** [comment] 2017-02-08 07:57
Yes 0.0.8 version runs smoothly but it still  needs to apply the @vocivvy 's hack(Have to rearrange boot order, Network have to go before Optical)

**Comment by jackpot51** [comment] 2017-03-17 05:10
Duplicate of https://github.com/redox-os/redox/issues/868

**Closed by jackpot51** 2017-03-17 05:10 UTC
